# K8s Build Pod 配置
apiVersion: v1
kind: Pod
metadata:
  name: ${APP}-build
spec:
  restartPolicy: Never
  containers:
    - name: buildah
      image: quay.io/buildah/stable:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      emptyDir: {}
