# Buildah 镜像源配置
# 中国镜像源配置，用于 Docker Hub、GCR、GHCR、Quay、MCR

unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "docker.io"
location = "registry.cdn.w7.cc"

[[registry]]
prefix = "gcr.io"
location = "gcr.m.daocloud.io"

[[registry]]
prefix = "ghcr.io"
location = "ghcr.m.daocloud.io"

[[registry]]
prefix = "quay.io"
location = "quay.nju.edu.cn"

[[registry]]
prefix = "mcr.microsoft.com"
location = "mcr.m.daocloud.io"
